Repository DSSGxDFKI/surveyweathertool-dssg23-jumpstart, pull requests merged in 2023-09, with the labels that each got.

#1 Update dashboard to avoid OOM issues
  .streamlit/config.toml
  Docker-requirements.txt
  surveyweathertool/Home.py
  surveyweathertool/pages/1_📈_LSMS-ISA_Dashboard.py
  surveyweathertool/pages/2_📊_Weather_Data_Enhancement.py
  surveyweathertool/requirements.txt
  surveyweathertool/src/dashboard/utils.py
  surveyweathertool/src/weather/constants.py
  surveyweathertool/src/weather_x_survey/weather_survey.py
Labels: bug

#15 Update data structure, bringing in nice structure + tiny fixes
  docs/getting-started.rst
  surveyweathertool/get_weather_pipeline.py
  surveyweathertool/lsms_survey_pipeline.py
  surveyweathertool/pipeline.py
  surveyweathertool/src/dashboard/bivariate_maps.py
  surveyweathertool/src/dashboard/streamlit_app.py
  surveyweathertool/src/weather/constants.py
  surveyweathertool/src/weather/source_weather_data.py
  surveyweathertool/src/weather/utils.py
Labels: bug, documentation, soft-eng

#17 Update readme
  README.rst
Labels: documentation
